
services:
  db:
    image: postgres:16-alpine
    container_name: niaganow_db
    environment:
      POSTGRES_DB: NiagaNow
      POSTGRES_USER: niaganow
      POSTGRES_PASSWORD: strongpassword
    ports:
      - "5432:5432"
    volumes:
      - niaganow_db_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d  # opsional, untuk data awal admin
    networks:
      - niaganow_network

  redis:
    image: redis:7-alpine
    container_name: niaganow_redis
    ports:
      - "6379:6379"
    networks:
      - niaganow_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: niaganow-app:latest
    container_name: niaganow_app
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/NiagaNow
      SPRING_DATASOURCE_USERNAME: niaganow
      SPRING_DATASOURCE_PASSWORD: strongpassword
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    networks:
      - niaganow_network

volumes:
  niaganow_db_data:

networks:
  niaganow_network:
    driver: bridge
